<a href="https://colab.research.google.com/github/sandhya537/machine-learning/blob/main/train_and_test_datasets_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#---------------------------------creating an array--------------------------------------------

import numpy as np
ds=np.arange(10)
print (ds)


[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#------------------------------spliting dataset---------------------------------------------------

from sklearn.model_selection import train_test_split
import numpy as np

ds=np.arange(10)
print(ds)

result=train_test_split(ds)
print(result)



[0 1 2 3 4 5 6 7 8 9]
[array([6, 0, 2, 4, 9, 5, 1]), array([8, 7, 3])]


In [ ]:
#-----------------------------  using train test --------------------------------------

from sklearn.model_selection import train_test_split
import numpy as np

ds=np.arange(10)
print(ds)

ds_train,ds_test=train_test_split(ds)
print(ds_train)
print(ds_test)

[0 1 2 3 4 5 6 7 8 9]
[7 5 4 3 9 8 1]
[0 2 6]


In [ ]:
#------------------------------  using train size -------------------------------------


from sklearn.model_selection import train_test_split
import numpy as np

ds=np.arange(10)
print(ds)

ds_train,ds_test=train_test_split(ds,train_size=8)
print(ds_train)
print(ds_test)

[0 1 2 3 4 5 6 7 8 9]
[0 9 1 4 7 2 8 6]
[5 3]


In [ ]:
#------------------------------  using train size -------------------------------------
#-------------------practice 1-----------------------

from sklearn.model_selection import train_test_split
import numpy as np

ds=np.arange(10)
print(ds)

ds_train,ds_test=train_test_split(ds,train_size=0.6)
print(ds_train)
print(ds_test)

[0 1 2 3 4 5 6 7 8 9]
[6 3 8 5 0 9]
[2 4 1 7]


In [ ]:
#------------------------------  using test size -------------------------------------

from sklearn.model_selection import train_test_split
import numpy as np

ds=np.arange(10)
print(ds)

ds_train,ds_test=train_test_split(ds,test_size=4)
print(ds_train)
print(ds_test)

[0 1 2 3 4 5 6 7 8 9]
[5 6 9 2 8 7]
[4 3 1 0]


In [ ]:
#------------------------------  using test size -------------------------------------
#-------------------practice 1-----------------------

from sklearn.model_selection import train_test_split
import numpy as np

ds=np.arange(10)
print(ds)

X_train,X_test=train_test_split(ds,test_size=0.4)
print(X_train)
print(X_test)

[0 1 2 3 4 5 6 7 8 9]
[4 7 6 2 1 3]
[0 8 9 5]


In [ ]:
#------------------------------  using train size ,test size-------------------------------------

from sklearn.model_selection import train_test_split
import numpy as np

ds=np.arange(10)
print(ds)

X_train,X_test=train_test_split(ds,train_size=4,test_size=4)
print(X_train)
print(X_test)

[0 1 2 3 4 5 6 7 8 9]
[3 2 0 7]
[1 4 8 6]


In [ ]:
#------------------------------  using train, test -------------------------------------

from sklearn.model_selection import train_test_split
import numpy as np

ds=np.arange(10)
print(ds)

X_train,X_test=train_test_split(ds)
print(ds_train)
print(ds_test)

[0 1 2 3 4 5 6 7 8 9]
[6 1 7 5 0 4 8]
[3 2 9]


In [ ]:
#--------------------creating array size 20  -------------------------------------------

import numpy as np
ds=np.arange(20)
print(ds)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
#------------------------- using reshaping  -----------------------------------------------

import numpy as np
ds=np.arange(20)
print(ds)

ds1=np.arange(20).reshape(2,10)
print(ds1)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [ ]:
#-------------------- using T transpose - for reshape---------------------------------------

import numpy as np
ds=np.arange(20)
print(ds)

ds2=np.arange(20).reshape(2,10).T
print(ds2)



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0 10]
 [ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]
 [ 5 15]
 [ 6 16]
 [ 7 17]
 [ 8 18]
 [ 9 19]]


In [ ]:
#------------------------------  using reshape -------------------------------------
#-------------------practice 1-----------------------

import numpy as np
ds=np.arange(20)
print(ds)
print()

ds1=np.arange(20).reshape(2,10).T
print(ds1)
print()
y=np.arange(10)
print(y)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

[[ 0 10]
 [ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]
 [ 5 15]
 [ 6 16]
 [ 7 17]
 [ 8 18]
 [ 9 19]]

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#------------------------------  using train ,test 2 datasets -------------------------------------

import numpy as np
from sklearn.model_selection import train_test_split

X=np.arange(20).reshape(10,2)
print(X)

Y=np.arange(10)
print(Y)
print()
X_train,X_test,Y_train,Y_test=train_test_split(X,Y)

print(X_train)
print(X_test)
print()
print(Y_train)
print(Y_test)


[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]
[0 1 2 3 4 5 6 7 8 9]

[[ 2  3]
 [14 15]
 [ 4  5]
 [18 19]
 [ 6  7]
 [10 11]
 [16 17]]
[[12 13]
 [ 8  9]
 [ 0  1]]

[1 7 2 9 3 5 8]
[6 4 0]


In [ ]:
#------------------------------  using 3 datasets for test,train   -------------------------------------
#-------------------practice 1-----------------------

import numpy as np
from sklearn.model_selection import train_test_split

X=np.arange(10)
print(X)

Y=np.arange(10)
print(Y)

Z=np.arange(10)
print(Z)

print()
X_train,X_test,Y_train,Y_test,Z_train,Z_test=train_test_split(X,Y,Z)
print(X_train)
print(X_test)
print()
print(Y_train)
print(Y_test)
print()
print(Z_train)
print(Z_test)




[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]

[0 7 8 3 1 2 5]
[9 4 6]

[0 7 8 3 1 2 5]
[9 4 6]

[0 7 8 3 1 2 5]
[9 4 6]


In [ ]:
#------------------------------  using random_state=0  -------------------------------------

import numpy as np
from sklearn.model_selection import train_test_split

X=np.arange(20).reshape(2,10).T
print(X)

Y=np.arange(10)
print(Y)

print()
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,random_state=0)

print(X_train)
print(X_test)
print()
print(Y_train)
print(Y_test)

[[ 0 10]
 [ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]
 [ 5 15]
 [ 6 16]
 [ 7 17]
 [ 8 18]
 [ 9 19]]
[0 1 2 3 4 5 6 7 8 9]

[[ 9 19]
 [ 1 11]
 [ 6 16]
 [ 7 17]
 [ 3 13]
 [ 0 10]
 [ 5 15]]
[[ 2 12]
 [ 8 18]
 [ 4 14]]

[9 1 6 7 3 0 5]
[2 8 4]


In [8]:
#------------------------------  using 2 data sets -------------------------------------
#-------------------practice 2 reshape-----------------------

import numpy as np
from sklearn.model_selection import train_test_split

X=np.arange(10).reshape(10,1)
print(X)

Y=np.arange(10)
print(Y)
print()
X_train,X_test,Y_train,Y_test=train_test_split(X,Y)

print(X_train)
print(X_test)
print()
print(Y_train)
print(Y_test)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[0 1 2 3 4 5 6 7 8 9]

[[2]
 [0]
 [4]
 [1]
 [6]
 [7]
 [8]]
[[3]
 [5]
 [9]]

[2 0 4 1 6 7 8]
[3 5 9]
